- id: doi:10.1016/j.jml.2004.06.012
  image: https://ars.els-cdn.com/content/image/1-s2.0-S2001037020302804-gr1.jpg
  tags: 
    - Publication

- id: doi:10.1016/j.cognition.2005.04.004
  image: https://iiif.elifesciences.org/lax:32822%2Felife-32822-fig8-v3.tif/full/863,/0/default.webp

- id: doi:10.1016/j.cognition.2005.10.002

- id: doi:10.1016/j.lingua.2006.11.011

- id: doi:10.1016/j.actpsy.2006.09.008

- title: 응시 단서를 이용한 학령기 전 아동의 타인의 선호 이해
  authors:
    - 김유진
    - 송현주
  publisher: "한국심리학회지: 발달"
  date: 2007-12-01
  link: https://www.kci.go.kr/kciportal/ci/sereArticleSearch/ciSereArtiView.kci?sereArticleSearchBean.artiId=ART001088648

- id: doi:10.22172/cogbio.2007.19.4.008

- title: 아동의 행위자 성향 추론 능력의 발달
  authors:
    - 윤정은
    - 송현주
  publisher: "한국심리학회지: 일반"
  date: 2007-12-01
  link: https://www.kci.go.kr/kciportal/ci/sereArticleSearch/ciSereArtiView.kci?sereArticleSearchBean.artiId=ART001207012

- title: "3, 4세 한국 아동의 단어 학습에서 상호배타성과 화용 단서의 역할"
  authors:
    - 진경선
    - 김민영
    - 김유진
    - 윤정은
    - 송현주
  publisher: "한국심리학회지: 발달"
  date: 2008-02-01
  link: https://www.kci.go.kr/kciportal/ci/sereArticleSearch/ciSereArtiView.kci?sereArticleSearchBean.artiId=ART001245646

- title: "통계 조사 방법에 대한 인지심리학적 접근: 선택지의 개수와 순서에 따른 응답의 변화"
  authors:
    - 이경수
    - 송현주
    - 손영우
    - 황명진
    - 박영실
  publisher: 통계연구
  date: 2008-06-01
  link: https://www.kci.go.kr/kciportal/ci/sereArticleSearch/ciSereArtiView.kci?sereArticleSearchBean.artiId=ART001318416

- title: "타인의 가리키기 행동 목표 이해의 발달: 7, 9개월 영아 자료"
  authors:
    - "김민영"
    - "송현주"
  publisher: "한국심리학회지: 발달"
  date: 2008-06-01
  link: https://www.kci.go.kr/kciportal/landing/article.kci?arti_id=ART001277560

- title: "아동 특질의 본질에 대한 한국 성인의 믿음"
  authors:
    - "최유정"
    - "송현주"
  publisher: "한국심리학회지: 발달"
  date: 2008-06-01
  link: https://www.kci.go.kr/kciportal/ci/sereArticleSearch/ciSereArtiView.kci?sereArticleSearchBean.artiId=ART001278302

- title: "한국어에서 담화정보가 학령 전 아동의 문장 이해에 미치는 영향"
  authors:
    - "송현주"
    - "최유정"
    - "김민영"
  publisher: "한국심리학회지: 발달"
  date: 2008-06-01
  link: https://www.kci.go.kr/kciportal/ci/sereArticleSearch/ciSereArtiView.kci?sereArticleSearchBean.artiId=ART001277562

- id: doi:10.1037/a0013774

- id: doi:10.1016/j.cognition.2008.08.008

- id: doi:10.1016/j.cognition.2008.07.019

- title: "한국어 문장 처리에 있어서 담화 정보의 영향"
  authors:
    - "이우열"
    - "송현주"
  publisher: "언어사실과 관점"
  date: 2009-11-01
  link: https://kiss.kstudy.com/Detail/Ar?key=2952122

- title: "형태론적 단서가 만 2세 아동의 새로운 동사학습에 미치는 영향"
  authors:
    - "이우열"
    - "송현주"
  publisher: "한국심리학회지: 발달"
  date: 2009-01-01
  link: https://www.kci.go.kr/kciportal/ci/sereArticleSearch/ciSereArtiView.kci?sereArticleSearchBean.artiId=ART001395832
  
- title: "타인의 감정, 바람, 친사회적 행동에 대한 한국 아동의 이해"
  authors:
    - "원정애"
    - "송현주"
  publisher: "한국심리학회지: 발달"
  date: 2009-04-01
  link: https://www.kci.go.kr/kciportal/ci/sereArticleSearch/ciSereArtiView.kci?sereArticleSearchBean.artiId=ART001395828

- title: "한국 아동들의 조사를 이용한 새로운 명사 학습"
  authors:
    - "이윤하"
    - "송현주"
  publisher: "한국심리학회지: 발달"
  date: 2010-01-01
  link: https://www.kci.go.kr/kciportal/ci/sereArticleSearch/ciSereArtiView.kci?sereArticleSearchBean.artiId=ART001427739

- title: "만 3, 4세 아동들의 거짓말 이해와 사실추론 능력"
  authors:
    - "김윤"
    - "송현주"
  publisher: "한국심리학회지: 발달"
  date: 2010-01-01
  link: https://www.kci.go.kr/kciportal/ci/sereArticleSearch/ciSereArtiView.kci?sereArticleSearchBean.artiId=ART001477754

- title: "한국 아동과 성인의 처소격 조사를 활용한 공간 명사의 의미 이해"
  authors:
    - "이윤하"
    - "송현주"
  publisher: "한국심리학회지: 발달"
  date: 2010-01-01
  link: https://www.kci.go.kr/kciportal/ci/sereArticleSearch/ciSereArtiView.kci?sereArticleSearchBean.artiId=ART001500339

- id: doi:10.1016/j.cogpsych.2010.09.001

- title: "Infants Expect Others to Help One Another Achieve a Goal"
  authors:
    - "Lee, W."
    - "Kim, E. Y."
    - "Won, J."
    - "Lee, Y."
    - "Kim, Y"
  publisher: "Proceedings of the 32nd Annual Conference of the Cognitive Science Society"
  date: 2010-01-01

- title: "만 14개월 한국 영아들의 합리적 모방 능력"
  authors:
    - "김은영"
    - "송현주"
  publisher: "한국심리학회지: 발달"
  date: 2011-06-01
  link: https://www.kci.go.kr/kciportal/ci/sereArticleSearch/ciSereArtiView.kci?sereArticleSearchBean.artiId=ART001557692

- title: "인종 정보에 따른 한국 영아의 얼굴 인식 발달"
  authors:
    - "김윤"
    - "송현주"
  publisher: "한국심리학회지: 발달"
  date: 2011-09-01
  link: https://www.kci.go.kr/kciportal/landing/article.kci?arti_id=ART001586300

- title: "형태론적 정보를 활용한 만 3세 아동의 타인행동 모방능력"
  authors:
    - "김은영"
    - "송현주"
  publisher: "한국심리학회지: 발달"
  date: 2011-11-01
  link: https://www.kci.go.kr/kciportal/ci/sereArticleSearch/ciSereArtiView.kci?sereArticleSearchBean.artiId=ART001608385
