- id: doi:10.1016/j.jml.2004.06.012
  image: https://ars.els-cdn.com/content/image/1-s2.0-S2001037020302804-gr1.jpg
  tags: 
    - Paper
- id: doi:10.1016/j.cognition.2005.04.004
  image: https://iiif.elifesciences.org/lax:32822%2Felife-32822-fig8-v3.tif/full/863,/0/default.webp
  tags: 
    - Paper

- id: doi:10.1016/j.cognition.2005.10.002
  tags: 
    - Paper

- id: doi:10.1016/j.lingua.2006.11.011
  tags: 
    - Paper

- id: doi:10.1016/j.actpsy.2006.09.008
  tags: 
    - Paper

- title: 응시 단서를 이용한 학령기 전 아동의 타인의 선호 이해
  authors:
    - 김유진
    - 송현주
  publisher: "한국심리학회지: 발달"
  date: 2007-12-01
  link: https://www.kci.go.kr/kciportal/ci/sereArticleSearch/ciSereArtiView.kci?sereArticleSearchBean.artiId=ART001088648
  tags: 
    - Paper

- id: doi:10.22172/cogbio.2007.19.4.008
  tags: 
    - Paper

- title: 아동의 행위자 성향 추론 능력의 발달
  authors:
    - 윤정은
    - 송현주
  publisher: "한국심리학회지: 일반"
  date: 2007-12-01
  link: https://www.kci.go.kr/kciportal/ci/sereArticleSearch/ciSereArtiView.kci?sereArticleSearchBean.artiId=ART001207012
  tags: 
    - Paper

- title: "3, 4세 한국 아동의 단어 학습에서 상호배타성과 화용 단서의 역할"
  authors:
    - 진경선
    - 김민영
    - 김유진
    - 윤정은
    - 송현주
  publisher: "한국심리학회지: 발달"
  date: 2008-02-01
  link: https://www.kci.go.kr/kciportal/ci/sereArticleSearch/ciSereArtiView.kci?sereArticleSearchBean.artiId=ART001245646
  tags: 
    - Paper

- title: "통계 조사 방법에 대한 인지심리학적 접근: 선택지의 개수와 순서에 따른 응답의 변화"
  authors:
    - 이경수
    - 송현주
    - 손영우
    - 황명진
    - 박영실
  publisher: 통계연구
  date: 2008-06-01
  link: https://www.kci.go.kr/kciportal/ci/sereArticleSearch/ciSereArtiView.kci?sereArticleSearchBean.artiId=ART001318416
  tags: 
    - Paper

- title: "타인의 가리키기 행동 목표 이해의 발달: 7, 9개월 영아 자료"
  authors:
    - "김민영"
    - "송현주"
  publisher: "한국심리학회지: 발달"
  date: 2008-06-01
  link: https://www.kci.go.kr/kciportal/landing/article.kci?arti_id=ART001277560
  tags: 
    - Paper

- title: "아동 특질의 본질에 대한 한국 성인의 믿음"
  authors:
    - "최유정"
    - "송현주"
  publisher: "한국심리학회지: 발달"
  date: 2008-06-01
  link: https://www.kci.go.kr/kciportal/ci/sereArticleSearch/ciSereArtiView.kci?sereArticleSearchBean.artiId=ART001278302
  tags: 
    - Paper

- title: "한국어에서 담화정보가 학령 전 아동의 문장 이해에 미치는 영향"
  authors:
    - "송현주"
    - "최유정"
    - "김민영"
  publisher: "한국심리학회지: 발달"
  date: 2008-06-01
  link: https://www.kci.go.kr/kciportal/ci/sereArticleSearch/ciSereArtiView.kci?sereArticleSearchBean.artiId=ART001277562
  tags: 
    - Paper

- id: doi:10.1037/a0013774
  tags: 
    - Paper

- id: doi:10.1016/j.cognition.2008.08.008
  tags: 
    - Paper

- id: doi:10.1016/j.cognition.2008.07.019
  tags: 
    - Paper

- title: "한국어 문장 처리에 있어서 담화 정보의 영향"
  authors:
    - "이우열"
    - "송현주"
  publisher: "언어사실과 관점"
  date: 2009-11-01
  link: https://kiss.kstudy.com/Detail/Ar?key=2952122
  tags: 
    - Paper

- title: "형태론적 단서가 만 2세 아동의 새로운 동사학습에 미치는 영향"
  authors:
    - "이우열"
    - "송현주"
  publisher: "한국심리학회지: 발달"
  date: 2009-01-01
  link: https://www.kci.go.kr/kciportal/ci/sereArticleSearch/ciSereArtiView.kci?sereArticleSearchBean.artiId=ART001395832
  tags: 
    - Paper
  
- title: "타인의 감정, 바람, 친사회적 행동에 대한 한국 아동의 이해"
  authors:
    - "원정애"
    - "송현주"
  publisher: "한국심리학회지: 발달"
  date: 2009-04-01
  link: https://www.kci.go.kr/kciportal/ci/sereArticleSearch/ciSereArtiView.kci?sereArticleSearchBean.artiId=ART001395828
  tags: 
    - Paper

- title: "한국 아동들의 조사를 이용한 새로운 명사 학습"
  authors:
    - "이윤하"
    - "송현주"
  publisher: "한국심리학회지: 발달"
  date: 2010-01-01
  link: https://www.kci.go.kr/kciportal/ci/sereArticleSearch/ciSereArtiView.kci?sereArticleSearchBean.artiId=ART001427739
  tags: 
    - Paper

- title: "만 3, 4세 아동들의 거짓말 이해와 사실추론 능력"
  authors:
    - "김윤"
    - "송현주"
  publisher: "한국심리학회지: 발달"
  date: 2010-01-01
  link: https://www.kci.go.kr/kciportal/ci/sereArticleSearch/ciSereArtiView.kci?sereArticleSearchBean.artiId=ART001477754
  tags: 
    - Paper

- title: "한국 아동과 성인의 처소격 조사를 활용한 공간 명사의 의미 이해"
  authors:
    - "이윤하"
    - "송현주"
  publisher: "한국심리학회지: 발달"
  date: 2010-01-01
  link: https://www.kci.go.kr/kciportal/ci/sereArticleSearch/ciSereArtiView.kci?sereArticleSearchBean.artiId=ART001500339
  tags: 
    - Paper

- id: doi:10.1016/j.cogpsych.2010.09.001
  tags: 
    - Paper

- title: "Infants Expect Others to Help One Another Achieve a Goal"
  authors:
    - "Lee, W."
    - "Kim, E. Y."
    - "Won, J."
    - "Lee, Y."
    - "Kim, Y"
  publisher: "Proceedings of the 32nd Annual Conference of the Cognitive Science Society"
  date: 2010-01-01
  tags: 
    - Paper

- title: "만 14개월 한국 영아들의 합리적 모방 능력"
  authors:
    - "김은영"
    - "송현주"
  publisher: "한국심리학회지: 발달"
  date: 2011-06-01
  link: https://www.kci.go.kr/kciportal/ci/sereArticleSearch/ciSereArtiView.kci?sereArticleSearchBean.artiId=ART001557692
  tags: 
    - Paper

- title: "인종 정보에 따른 한국 영아의 얼굴 인식 발달"
  authors:
    - "김윤"
    - "송현주"
  publisher: "한국심리학회지: 발달"
  date: 2011-09-01
  link: https://www.kci.go.kr/kciportal/landing/article.kci?arti_id=ART001586300
  tags: 
    - Paper

- title: "형태론적 정보를 활용한 만 3세 아동의 타인행동 모방능력"
  authors:
    - "김은영"
    - "송현주"
  publisher: "한국심리학회지: 발달"
  date: 2011-11-01
  link: https://www.kci.go.kr/kciportal/ci/sereArticleSearch/ciSereArtiView.kci?sereArticleSearchBean.artiId=ART001608385
  tags: 
    - Paper

- title: "한국 영아의 영어 음소 /l/-/r/ 변별에 대한 ERP 연구"
  authors: 
    - "김은영"
    - "김효림"
    - "송현주"
    - "전영미"
    - "최영은"
  publisher: "언어과학"
  date: 2012-02-01
  link: https://www.kci.go.kr/kciportal/ci/sereArticleSearch/ciSereArtiView.kci?sereArticleSearchBean.artiId=ART001635871
  tags: 
    - Paper

- title: "언어 정보를 이용한 만 7개월 한국 영아들의 가리키기 행동의 목표 지향성 이해 능력"
  authors: 
    - "이지현"
    - "김민영"
    - "송현주"
  publisher: "한국심리학회지: 발달"
  date: 2012-02-01
  link: https://kci.go.kr/kciportal/landing/article.kci?arti_id=ART001642241
  tags: 
    - Paper

- title: "만 3세 한국 아동들의 타인 조망 수용 능력과 새로운 단어 학습"
  authors: 
    - "전영미"
    - "송현주"
  publisher: "한국심리학회지: 발달"
  date: 2012-05-01
  link: https://www.kci.go.kr/kciportal/ci/sereArticleSearch/ciSereArtiView.kci?sereArticleSearchBean.artiId=ART001667793
  tags:
    - Paper

- title: "5-6세 한국 아동의 보조사 '도'와 '만'의 이해 능력"
  authors: 
    - "조이수"
    - "송현주"
  publisher: "언어과학"
  date: 2013-02-01
  link: https://www.kci.go.kr/kciportal/ci/sereArticleSearch/ciSereArtiView.kci?sereArticleSearchBean.artiId=ART001743736
  tags:
    - Paper

- title: "양보 행동 동기가 감정에 미치는 영향에 대한 한국 성인과 학령 전기 아동의 이해"
  authors: 
    - "윤지영"
    - "송현주"
  publisher: "한국심리학회지: 발달"
  date: 2013-02-01
  link: https://www.kci.go.kr/kciportal/ci/sereArticleSearch/ciSereArtiView.kci?sereArticleSearchBean.artiId=ART001750867
  tags:
    - Paper

- title: "한국 성인 및 만 4세 아동의 분배 상황 평가 시 비율적 사고 능력"
  authors: 
    - "김효림"
    - "송현주"
  publisher: "한국심리학회지: 발달"
  date: 2013-02-01
  link: https://www.kci.go.kr/kciportal/landing/article.kci?arti_id=ART001750858
  tags:
    - Paper

- title: "한국 아동의 문장 구조 정보를 활용한 문장 이해 능력의 발달"
  authors: 
    - "이우열"
    - "김민주"
    - "송현주"
  publisher: "한국심리학회지: 발달"
  date: 2013-12-01
  link: https://www.kci.go.kr/kciportal/ci/sereArticleSearch/ciSereArtiView.kci?sereArticleSearchBean.artiId=ART001826159
  tags:
    - Paper

- id: doi:10.1080/10489223.2013.828059
  tags: 
    - Paper

- id: doi:10.1111/cdep.12032
  tags: 
    - Paper

- id: doi:10.1371/journal.pone.0092387
  tags:
    - Paper

- title: "착한 거짓말과 나쁜 참말? 5-6세 아동의 상황에 따른 거짓말과 참말 이해"
  authors: 
    - "송미리"
    - "송현주"
  publisher: "한국심리학회지: 발달"
  date: 2014-02-01
  link: https://www.kci.go.kr/kciportal/ci/sereArticleSearch/ciSereArtiView.kci?sereArticleSearchBean.artiId=ART001858626
  tags:
    - Paper

- title: "감정 고려가 만 4세 아동의 분배 행동에 미치는 효과"
  authors: 
    - "유하나"
    - "이지현"
    - "송현주"
    - "김영훈"
  publisher: "한국심리학회지: 발달"
  date: 2014-06-01
  link: https://www.kci.go.kr/kciportal/ci/sereArticleSearch/ciSereArtiView.kci?sereArticleSearchBean.artiId=ART001881737
  tags:
    - Paper

- title: "거짓말과 참말 이해에 대한 상황적 요인의 영향: 4세 아동의 자료"
  authors: 
    - "송미리"
    - "송현주"
  publisher: "한국심리학회지: 발달"
  date: 2014-06-01
  link: https://www.kci.go.kr/kciportal/ci/sereArticleSearch/ciSereArtiView.kci?sereArticleSearchBean.artiId=ART001881736
  tags:
    - Paper

- title: "강화학습과제에서의 어머니의 이타적 성향과 자녀의 공감 간의 관계"
  authors: 
    - "김은영"
    - "설선혜"
    - "유하나"
    - "김학진"
    - "송현주"
  publisher: "한국심리학회지: 여성"
  date: 2014-06-01
  link: https://www.kci.go.kr/kciportal/ci/sereArticleSearch/ciSereArtiView.kci?sereArticleSearchBean.artiId=ART001895512
  tags:
    - Paper

- title: "영아의 도움 행동과 방해 행동의 의도 이해"
  authors: 
    - "이영은"
    - "송현주"
  publisher: "인지과학"
  date: 2014-06-01
  link: https://www.kci.go.kr/kciportal/ci/sereArticleSearch/ciSereArtiView.kci?sereArticleSearchBean.artiId=ART001893829
  tags:
    - Paper

- title: "가리키기 행동 이해에 기반을 둔 12개월 영아들의 행동 목표 예측 능력"
  authors: 
    - "김은영"
    - "송현주"
  publisher: "한국심리학회지: 발달"
  date: 2014-12-01
  link: https://www.kci.go.kr/kciportal/landing/article.kci?arti_id=ART001935309
  tags:
    - Paper

- title: "한국인 프랑스어 학습자의 프랑스어 담화 이해와 대명사 해석 연구"
  authors: 
    - "안의진"
    - "송현주"
    - "김민주"
    - "임재호"
  publisher: "인지과학"
  date: 2014-12-01
  link: https://www.kci.go.kr/kciportal/ci/sereArticleSearch/ciSereArtiView.kci?sereArticleSearchBean.artiId=ART001956389
  tags:
    - Paper
    
- id: doi:10.1016/j.cogdev.2014.09.003
  tags:
    - Paper

- title: "만 10개월 영아들의 언어적 단서를 활용한 타인의 목표 행동 이해"
  authors: 
    - "김민주"
    - "송현주"
  publisher: "한국심리학회지: 발달"
  date: 2015-06-01
  link: https://www.kci.go.kr/kciportal/ci/sereArticleSearch/ciSereArtiView.kci?sereArticleSearchBean.artiId=ART001997441
  tags:
    - Paper

- title: "5-6세 아동의 분배 결정에 내집단 선호가 미치는 영향"
  authors: 
    - "차민정"
    - "송현주"
  publisher: "인지과학"
  date: 2015-06-01
  link: https://www.kci.go.kr/kciportal/ci/sereArticleSearch/ciSereArtiView.kci?sereArticleSearchBean.artiId=ART002005655
  tags:
    - Paper

- title: "형태론적 언어 정보 활용을 통한 타인행동 목표 추론 능력의 영아기 발달"
  authors: 
    - "김은영"
    - "송현주"
  publisher: "한국심리학회지: 발달"
  date: 2015-06-01
  link: https://www.kci.go.kr/kciportal/landing/article.kci?arti_id=ART001997448
  tags:
    - Paper

- id: doi:10.1371/journal.pone.0135588
  tags:
    - paper

- title: "한국형 성인 우수영어학습자 학습자특성에 관한 사례연구"
  authors: 
    - "이희경"
    - "신수정"
    - "황명환"
    - "김민주"
    - "이현아"
    - "송현주"
  publisher: "현대영어교육"
  date: 2015-09-01
  link: https://www.kci.go.kr/kciportal/ci/sereArticleSearch/ciSereArtiView.kci?sereArticleSearchBean.artiId=ART002020326
  tags:
    - Paper

- title: "한국인 EFL 성인 고급 학습자들의 담화 맥락에서의 대명사 이해"
  authors: 
    - "김민주"
    - "안의진"
    - "송현주"
  publisher: "언어과학"
  date: 2015-09-01
  link: https://www.kci.go.kr/kciportal/ci/sereArticleSearch/ciSereArtiView.kci?sereArticleSearchBean.artiId=ART002021894
  tags:
    - Paper

- title: "한국 유아의 격조사를 활용한 타동사 문장 이해 발달"
  authors: 
    - "진경선"
    - "김민주"
    - "송현주"
  publisher: "한국심리학회지: 발달"
  date: 2015-09-01
  link: https://www.kci.go.kr/kciportal/ci/sereArticleSearch/ciSereArtiView.kci?sereArticleSearchBean.artiId=ART002028789
  tags:
    - Paper

- title: "만 24개월 영아의 도움, 나눔 행동의 발달"
  authors: 
    - "진경선"
    - "김민주"
    - "송현주"
  publisher: "한국유아교육학회"
  date: 2015-12-01
  link: https://www.kci.go.kr/kciportal/ci/sereArticleSearch/ciSereArtiView.kci?sereArticleSearchBean.artiId=ART002069613
  tags:
    - Paper

- title: "만 5-6세 한국 아동의 사회비교에 영향을 주는 양육자 요인"
  authors: 
    - "김은영"
    - "송현주"
  publisher: "한국심리학회지: 발달"
  date: 2016-02-01
  link: https://www.kci.go.kr/kciportal/ci/sereArticleSearch/ciSereArtiView.kci?sereArticleSearchBean.artiId=ART002089530
  tags:
    - Paper

- title: "단일 언어 사용 2-3세 아동의 외국어 단어에 대한 이해"
  authors: 
    - "이현아"
    - "김은영"
    - "송현주"
  publisher: "아동학회지"
  date: 2016-12-01
  link: https://www.dbpia.co.kr/journal/articleDetail?nodeId=NODE07084831
  tags:
    - Paper

- title: "조기 외국어 노출이 영아기 언어의 관습성 이해 발달에 미치는 영향"
  authors: 
    - "이윤미"
    - "송현주"
  publisher: "한국심리학회지: 발달"
  date: 2016-09-01
  link: https://www.kci.go.kr/kciportal/ci/sereArticleSearch/ciSereArtiView.kci?sereArticleSearchBean.artiId=ART002144332
  tags:
    - Paper

- title: "상호배타성 가정의 선택적 사용 능력의 발달: 2세와 3세 아동 비교 연구"
  authors: 
    - "이현아"
    - "김은영"
    - "송현주"
  publisher: "한국심리학회지: 발달"
  date: 2017-02-01
  link: https://www.kci.go.kr/kciportal/ci/sereArticleSearch/ciSereArtiView.kci?sereArticleSearchBean.artiId=ART002205867
  tags:
    - Paper

- title: "단체카톡방 언어성폭력에 대한 태도 연구"
  authors: 
    - "진경선"
    - "김수연"
    - "정유경"
    - "송현주"
    - "송민"
  publisher: "한국심리학회지: 여성"
  date: 2017-06-01
  link: https://www.kci.go.kr/kciportal/landing/article.kci?arti_id=ART002240466
  tags:
    - Paper

- title: "타인의 단어와 행동 목표의 관계성에 대한 10개월 영아의 이해에 있어서 사회정서 단서의 영향"
  authors: 
    - "이윤미"
    - "김민주"
    - "송현주"
  publisher: "아동학회지"
  date: 2017-06-01
  link: https://www.kci.go.kr/kciportal/ci/sereArticleSearch/ciSereArtiView.kci?sereArticleSearchBean.artiId=ART002199656
  tags:
    - Paper

- id: doi:10.1016/j.jecp.2017.05.001
  tags:
    - Paper

- title: "도움 행동이 유발하는 정서에 대한 관찰자의 영향: 성인과 만 4-5세 아동의 자료"
  authors: 
    - "김현정"
    - "송현주"
  publisher: "한국심리학회지: 발달"
  date: 2017-09-01
  link: https://www.kci.go.kr/kciportal/landing/article.kci?arti_id=ART002261898
  tags:
    - Paper
