- id: doi:10.1016/j.jml.2004.06.012
  image: https://ars.els-cdn.com/content/image/1-s2.0-S2001037020302804-gr1.jpg

- id: doi:10.1016/j.cognition.2005.04.004
  image: https://iiif.elifesciences.org/lax:32822%2Felife-32822-fig8-v3.tif/full/863,/0/default.webp

- id: doi:10.1016/j.cognition.2005.10.002

- id: doi:10.1016/j.lingua.2006.11.011

- id: doi:10.1016/j.actpsy.2006.09.008

- title: 응시 단서를 이용한 학령기 전 아동의 타인의 선호 이해
  authors:
    - 김유진
    - "**송현주**"
  publisher: "한국심리학회지:발달"
  date: 2007-12-01
